[CREATE] : 장바구니 기능 구현
wecode-bootcamp-korea/27-1st-FRA-WE-TAK-backend pull request #10
Opened 2021-12-04 13:40 UTC by jincastle

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [O] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 장바구니 추가, 개수변경, 조회 기능 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. get 기능으로 user_id를 filter을 걸어 상품 목록을 구현
   - cart로 해당 유저에 대한 필터로 로그인한 유저가 등록한 상품으로 추려낸다
   - cart에서 상품의 정참조를 이용하여 제품의 정보를 출력한다
2. post 장바구니 담기를 할시 cart에서 생성 구현
   - 장바구니 담기 누를시 카트에 생성 
3. patch + - 버튼 을 프론트에서 받아 개수 조절 구현
  - + - 버튼을 프론트에서 post로 받아 개수 조절 예정
4. delete 삭제 버튼 누르면 목록에서 삭제 처리 구현
 - 삭제 버튼을 프론트에서 post로 받아 개수 조절 진행

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 개수 변경자체가 db를 계속 건들기 때문에 해결이 필요해 보입니다.
- 개수가 1미만으로 넘어갈시 삭제하도록 만들어도 괜찮을거 같습니다.
- 로그인 안할시 장바구니 사용방법도 생각이 필요해 보입니다.

<br />

## :: 기타 질문 및 특이 사항
- db를 안 건드리고 개수 조절 방법이 궁금합니다

2021-12-05 14:44 UTC, bigfanoftim requested changes

2021-12-05 14:44 UTC, bigfanoftim commented on orders/views.py
> +            carts  = Cart.objects.filter(user_id = request.user_id)
테스트를 해보셨을까요? 코드에 오류가 있어보입니다
```suggestion
            carts  = Cart.objects.filter(user_id = request.user.id)
```

2021-12-05 14:44 UTC, bigfanoftim commented on orders/views.py
> +                user_id        = request.user.id,
suggestion과 같이 바로 user instance를 입력해주셔도 됩니다.
```suggestion
                user           = request.user,
```

2021-12-05 14:44 UTC, bigfanoftim commented on orders/views.py
> +    def patch(self, request, cart_id):
`cart_id`를 받아오는 엔드포인트는 작성하지 않으신 것 같습니다. PR 올리시기 전 꼭 테스트를 진행해주세요.

2021-12-07 06:18 UTC, bigfanoftim requested changes

2021-12-07 06:18 UTC, bigfanoftim commented on orders/views.py
> +            return JsonResponse({'message' : 'SUCCESS'}, status=201)
status code 201은 인증이 성공했을 때의 코드입니다. 성공 메세지에 맞게 수정해주세요.
```suggestion
            return JsonResponse({'message' : 'SUCCESS'}, status=200)
```

2021-12-07 10:31 UTC, lordmyshepherd approved these changes
LGTM 👍🏻

2021-12-07 10:32 UTC, merged