[27기 박재용] ListViewPage
wecode-bootcamp-korea/27-1st-FRA-WE-TAK-backend pull request #11
Opened 2021-12-04 15:18 UTC by yajkrap

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- ListViewPage에 필요한 정보들 호출

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
- List페이지 제작에 필요한 데이터 가져오기.

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 가져올 데이터를 확장성 있게 생각해 지금 당장 필요한 데이터 뿐 아니라 후에 필요할 수도 있는 여러 데이터를 불러오는 것에 대해 고민하게 되었습니다.

<br />

## :: 기타 질문 및 특이 사항

2021-12-06 06:43 UTC, bigfanoftim requested changes

2021-12-06 06:43 UTC, bigfanoftim commented on db_update.py
> +import os
csv 관련 파일 gitignore에 추가해주세요

2021-12-06 06:43 UTC, bigfanoftim commented on products/views.py
> +class ListPageView(View):
view는 페이지 단위가 아닌 기능별로 작성해주세요 그에 맞게 네이밍해주시고, 엔드포인트 주소도 수정해주세요~

2021-12-06 06:43 UTC, bigfanoftim commented on products/views.py
> +class ListPageView(View):
해당 내용에 대해 진성님께 많은 피드백 드렸으니 함께 이야기 나눠보시면 좋을 것 같습니다 재용님!

2021-12-06 06:43 UTC, bigfanoftim commented on users/urls.py
> +   # path('/login', LoginView.as_view())
불필요한 주석 제거해주세요~

2021-12-06 09:33 UTC, bigfanoftim requested changes

2021-12-06 09:33 UTC, bigfanoftim commented on products/urls.py
> +    path('/main/<int:sub_category_id>',SubCategoryView.as_view())
view는 페이지 단위가 아닌 기능별로 작성해주세요 그에 맞게 네이밍해주시고, 엔드포인트 주소도 수정해주세요. 해당 내용에 대해 진성님께 많은 피드백 드렸으니 함께 이야기 나눠보시면 좋을 것 같습니다.

2021-12-06 09:33 UTC, bigfanoftim commented on products/views.py
> +class SubCategoryView(View):
view는 페이지 단위가 아닌 기능별로 작성해주세요 그에 맞게 네이밍해주시고, 엔드포인트 주소도 수정해주세요. 해당 내용에 대해 진성님께 많은 피드백 드렸으니 함께 이야기 나눠보시면 좋을 것 같습니다.

2021-12-07 01:51 UTC, bigfanoftim requested changes

2021-12-07 01:51 UTC, bigfanoftim commented on products/views.py
> +class CategoryListView(View):
작성하신 코드를 보면 카테고리가 아니라 프로덕트 리스트인 것 같은데 맞을까요?
```suggestion
class ProductListView(View):
```

2021-12-07 01:51 UTC, bigfanoftim commented on products/urls.py
> +    path('/main/<int:sub_category_id>',CategoryListView.as_view())
페이지 단위로 view를 작성하는 것이 아닙니다. 기능별로 작성하여 그에 맞게 엔드포인트도 작성해주세요
```suggestion
    path('/category/<int:sub_category_id>', ProductListView.as_view())
```

2021-12-07 02:12 UTC, yajkrap commented on products/urls.py
> +    path('/main/<int:sub_category_id>',CategoryListView.as_view())
아 이해했습니다!!

2021-12-07 06:19 UTC, bigfanoftim approved these changes

2021-12-07 06:19 UTC, merged