[CREATE]:Login-Decorator기능구현
wecode-bootcamp-korea/27-1st-FRA-WE-TAK-backend pull request #13
Opened 2021-12-06 07:59 UTC by yoohyeoni

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ 0 ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 아이디, 비밀번호 입력창을 사용한 로그인 기능 구현 (예시)

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 로그인 데코레이터 적용

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 

<br />

## :: 기타 질문 및 특이 사항
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시)

2021-12-06 09:40 UTC, bigfanoftim requested changes

2021-12-06 09:40 UTC, bigfanoftim commented on FRA_WE_BACK/core/utils.py
> +            request.user = user
suggestion과 같이 한 번에 지정할 수 있을 것 같습니다.
```suggestion
            access_token = request.headers.get('Authorization', None)          
            payload      = jwt.decode(access_token, SECRET_KEY, algorithms='HS256')  
            request.user = User.objects.get(id=payload['id'])                 
```

2021-12-06 09:40 UTC, bigfanoftim commented on FRA_WE_BACK/core/utils.py
> +            return JsonResponse({'message' : 'INVALID_TOKEN', 'Token':access_token }, status=400)
DecodeError에 token을 전달해주는 이유가 있을까요?
```suggestion
            return JsonResponse({'message' : 'INVALID_TOKEN'}, status=400)
```

2021-12-06 09:40 UTC, bigfanoftim commented on FRA_WE_BACK/core/utils.py
> +def LogInDecorator(func):
함수는 클래스와 네이밍 컨벤션이 다릅니다. 확인해주세요
```suggestion
def log_in_decorator(func):
```

2021-12-06 09:40 UTC, bigfanoftim commented on FRA_WE_BACK/core/utils.py
> +from users.models             import User
```suggestion
import jwt

from django.http          import JsonResponse    

from FRA_WE_BACK.settings import SECRET_KEY                             
from users.models         import User
```

2021-12-07 01:24 UTC, lordmyshepherd approved these changes
LGTM 👍🏻

2021-12-07 01:24 UTC, merged