[박진성] 모델링 작업 완료
wecode-bootcamp-korea/27-1st-FRA-WE-TAK-backend pull request #2
Opened 2021-11-30 07:49 UTC by jincastle

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 아이디, 비밀번호 입력창을 사용한 로그인 기능 구현 (예시)

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 로그인 입력 데이터 유효성 검사 (예시 - 프론트)
- 입력창에 변화가 일어날 때 마다 유효성 검사 함수가 실행된다.
- 유효성 검사 함수의 반환값(boolean)에 따라 버튼의 배경색과 disabled 속성이 변화한다.
- 테스트 방법 : `/login` 페이지 이동 >>> 로그인 input 데이터 입력

2. 로그인 데이터 처리 (예시 - 백엔드)
- 조건문과 정규식을 이용한 email과 password 유효성 검사를 진행
- 유효섬 검사를 통과하지 못 할 경우 에러 메시지를 반환 예외 처리 구현

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 사용자가 발생시킬 수 있는 다양한 예외 케이스에 대해 고민하게 되었습니다. (예시)
- 문자열 데이터 입력 시 마지막에 빈 문자열이 포함되어 있는 경우 데이터 처리가 올바르게 되지 않아 유효성 검사에 빈 문자열 제거하는 로직을 추가하였습니다. (예시)

<br />

## :: 기타 질문 및 특이 사항
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시)

2021-11-30 09:45 UTC, lordmyshepherd requested changes

2021-11-30 09:45 UTC, lordmyshepherd commented on models/models.py
> +        db_table='product_category'
class명은 camelCase를 사용해주세요!
```suggestion
class ProductCategory(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        db_table='product_category'
```

2021-11-30 09:45 UTC, lordmyshepherd commented on orders/models.py
> +class OrderItems(models.Model):
Model class명은 단수로 만들어주세요!

```suggestion
class OrderItem(models.Model):
```

2021-11-30 09:45 UTC, lordmyshepherd commented on orders/models.py
> +    order_item_status = models.ForeignKey('Order_item_status', on_delete=models.CASCADE)
제대로 동작하나요?
ForeignKey 참조가 제대로 안된 것 같습니다.

```suggestion
    order_item_status = models.ForeignKey('OrderItemStatus', on_delete=models.CASCADE)
```

2021-11-30 09:54 UTC, jincastle commented on models/models.py
> +        db_table='product_category'
상품안에 카테고리가 하나이기 때문에 Category로 수정하였습니다

2021-11-30 09:54 UTC, jincastle commented on orders/models.py
> +class OrderItems(models.Model):
단수로 변경하였습니다.

2021-11-30 09:54 UTC, jincastle commented on orders/models.py
> +    order_item_status = models.ForeignKey('Order_item_status', on_delete=models.CASCADE)
참조값 수정하였습니다.

2021-11-30 09:55 UTC, bigfanoftim requested changes

2021-11-30 09:55 UTC, bigfanoftim commented on products/models.py
> +    like    = models.NullBooleanField()
좋아요 기능에 경우 True or False를 판단할 필요가 없습니다! likes 테이블 row의 존재 여부만으로 좋아요를 눌렀는지 안눌렀는지 판단할 수 있으니까요!!

2021-11-30 09:55 UTC, bigfanoftim commented on users/models.py
> +    email     = models.CharField(max_length=100)
`unique=True`!! 이메일은 중복될 수 없습니다!

2021-11-30 09:55 UTC, bigfanoftim commented on products/models.py
> +    update_at         = models.DateTimeField(auto_now=True)
`created_at`, `updated_at` 라고 다시 네이밍 해주세요! 꼭 지켜야 하는 룰은 아니지만, 많은 개발자들이 사용하는 convention 이므로 지켜주세요.

2021-11-30 09:56 UTC, bigfanoftim commented on products/models.py
> +    update_at         = models.DateTimeField(auto_now=True)
추가로 데이터 이력 관리가 필요한 테이블의 경우에도 `created_at`과 `updated_at` 컬럼을 추가해주세요!

2021-11-30 09:59 UTC, bigfanoftim commented
리뷰 내용 확인하시고 수정해서 migrate 후 데이터베이스 확인까지 꼭 거치고 리뷰 요청해주세요!

2021-11-30 10:29 UTC, jincastle commented on products/models.py
> +    update_at         = models.DateTimeField(auto_now=True)
넵 수정하였습니다

2021-11-30 10:29 UTC, jincastle commented on users/models.py
> +    email     = models.CharField(max_length=100)
이메일에 unique=True 추가하였습니다.

2021-11-30 10:30 UTC, jincastle commented on products/models.py
> +    like    = models.NullBooleanField()
감사합니다. like 삭제처리 하였습니다.

2021-11-30 11:10 UTC, jincastle commented on products/models.py
> +    update_at         = models.DateTimeField(auto_now=True)
order 이력이 필요해보여 추가하였습니다.

2021-12-01 01:26 UTC, bigfanoftim requested changes

2021-12-01 01:26 UTC, bigfanoftim commented on orders/models.py
> +        db_table = 'order_status'
```suggestion
        db_table = 'order_statuses'
```

2021-12-01 01:26 UTC, bigfanoftim commented on orders/models.py
> +        db_table = 'order_item_status'
```suggestion
        db_table = 'order_item_statuses'
```

2021-12-01 01:26 UTC, bigfanoftim commented on products/models.py
> +        db_table = 'maincategories'
```suggestion
        db_table = 'main_categories'
```

2021-12-01 01:26 UTC, bigfanoftim commented on products/models.py
> +        db_table = 'subcategories'
```suggestion
        db_table = 'sub_categories'
```

2021-12-01 01:26 UTC, bigfanoftim commented on orders/models.py
> +    order_status = models.ForeignKey('Order', on_delete=models.CASCADE)
Order 본인을 self 참조 하려고 하신걸까요?

2021-12-01 02:04 UTC, jincastle commented on orders/models.py
> +    order_status = models.ForeignKey('Order', on_delete=models.CASCADE)
OrderStatus 로 변경 했습니다.

2021-12-01 02:05 UTC, jincastle commented on products/models.py
> +        db_table = 'subcategories'
복수로 변경 완료했습니다

2021-12-01 02:05 UTC, jincastle commented on orders/models.py
> +        db_table = 'order_item_status'
복수로 변경완료 했습니다

2021-12-01 02:05 UTC, jincastle commented on orders/models.py
> +        db_table = 'order_status'
복수로 변경완료했습니다

2021-12-01 02:05 UTC, jincastle commented on products/models.py
> +        db_table = 'maincategories'
수정하였습니다

2021-12-01 03:28 UTC, bigfanoftim approved these changes
LGTM 😎

2021-12-01 03:29 UTC, merged