ADD : Mainpage category 별 이미지 출력 기능
wecode-bootcamp-korea/27-1st-FRA-WE-TAK-backend pull request #7
Opened 2021-12-03 05:00 UTC by jincastle

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [o ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 카테고리별 이미지 출력

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. maincategory_id 입력값에 따라 카테고리 분류하여 출력 

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
-  maincategory 이름 안에 리스트 + 딕션너리 형식으로 출력을 하고 싶었으나 따로 출력으로 하게됨
<br />

## :: 기타 질문 및 특이 사항

2021-12-03 06:29 UTC, bigfanoftim commented
진성님 프론트에는 SubCategory만 전달해주고 MainCategory는 하드코딩 하기로 되어있는건가요?

2021-12-03 10:26 UTC, jincastle commented
> 진성님 프론트에는 SubCategory만 전달해주고 MainCategory는 하드코딩 하기로 되어있는건가요?

넵 하기로 했지만 다시 상의하여 확장성을 고려해 백엔드 쪽에서 하기로 했습니다. 수정하도록 하겠습니다.

2021-12-03 12:11 UTC, bigfanoftim commented
conflict 해결 먼저 해주세요 진성님!

2021-12-03 12:22 UTC, jincastle commented
> conflict 해결 먼저 해주세요 진성님!
넵 해결했습니다

2021-12-05 14:30 UTC, bigfanoftim requested changes
진성님 그동안 전달된 피드백이 코드에 하나도 적용이 안된 모습입니다. Push 전에 다시 한 번 더 확인해주세요.

2021-12-05 14:30 UTC, bigfanoftim commented on products/views.py
> +class SubCategoryView(View):
SubCategory만 불러오는 View가 아닌 것 같은데요?

2021-12-05 14:30 UTC, bigfanoftim commented on products/views.py
> +        items   = MainCategory.objects.prefetch_related('subcategory_set')
items는 뭘 의미하는거죠?

2021-12-06 07:02 UTC, jincastle commented on products/views.py
> +class SubCategoryView(View):
넵 CategoryView 수정하였습니다.

2021-12-06 07:03 UTC, jincastle commented on products/views.py
> +        items   = MainCategory.objects.prefetch_related('subcategory_set')
변수명 변경했습니다.

2021-12-06 08:25 UTC, bigfanoftim approved these changes

2021-12-06 09:30 UTC, bigfanoftim approved these changes

2021-12-06 09:30 UTC, merged