[CREATE]:로그인기능구현
wecode-bootcamp-korea/27-1st-FRA-WE-TAK-backend pull request #9
Opened 2021-12-03 07:58 UTC by yoohyeoni

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ 0 ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 아이디, 비밀번호 입력창을 사용한 로그인 기능 구현 (예시)

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 로그인 기능구현
- 로그인 생성

2. 로그인 데이터 처리 
- 조건문과 정규식을 이용한 email과 password 유효성 검사를 진행

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 데코레이션까지 진행 예정..입니다....

<br />

## :: 기타 질문 및 특이 사항
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시)

2021-12-03 08:17 UTC, bigfanoftim requested changes

2021-12-03 08:17 UTC, bigfanoftim commented on users/views.py
> +            token = jwt.encode ({'id':user.id}, SECRET_KEY, algorithm='HS256')
알고리즘도 환경변수로 관리 해주시면 좋을 것 같습니다
```suggestion
            from FRA_WE_BACK.settings import SECRET_KEY, ALGORITHM
            '''
            token = jwt.encode ({'id':user.id}, SECRET_KEY, algorithm=ALGORITHM)
```

2021-12-03 08:18 UTC, bigfanoftim commented on users/views.py
> +            token = jwt.encode ({'id':user.id}, SECRET_KEY, algorithm='HS256')
수정해주시고 conflict 해결 후 push 해주세요~

2021-12-05 05:24 UTC, yoohyeoni commented on users/views.py
> +            token = jwt.encode ({'id':user.id}, SECRET_KEY, algorithm='HS256')
충돌 해결 수정했습니다.

2021-12-05 14:26 UTC, bigfanoftim requested changes

2021-12-05 14:26 UTC, bigfanoftim commented on FRA_WE_BACK/settings.py
> +ALGORITHM = os.environ['ALGORITHM']
수정해주세요
```suggestion
SECRET_KEY = os.environ['SECRET_KEY']
ALGORITHM  = os.environ['ALGORITHM']
```

2021-12-05 14:26 UTC, bigfanoftim commented on users/views.py
> +                "token" : token
수정해주세요
```suggestion
                'message' : 'success', 
                "token"   : token
```

2021-12-06 06:07 UTC, bigfanoftim approved these changes

2021-12-06 06:07 UTC, merged